In [ ]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Importing the dataset
data = pd.read_csv("/content/50_startups_data.csv")
data.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [ ]:
#Initiating the variables
X = data.drop(['Profit'], axis = 1)
Y = data['Profit'].values.reshape(-1,1)

In [ ]:
#Splitting data into training, testing datase
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=45)

In [ ]:
#Fitting Linear regression to our training set
from sklearn.linear_model import LinearRegression
multiple_reg = LinearRegression()
multiple_reg.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
#Testing
Y_pred = multiple_reg.predict(X_test)
Y_pred

array([[ 46591.4758872 ],
       [159877.39517991],
       [181942.82135806],
       [154668.71520182],
       [163444.84787177],
       [110396.28611962],
       [127477.12570991],
       [ 89724.16092738],
       [192480.59612014],
       [114912.5120704 ]])

In [ ]:
#Calculating the coefficients
multiple_reg.coef_


array([[ 0.7957237 , -0.02461232,  0.03042291]])

In [ ]:
#Calculating the intercept
multiple_reg.intercept_

array([49924.64611218])

In [29]:
#Calculating the R squared value
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

0.9836713364627709


Prediction for new values

In [53]:
output = multiple_reg.predict([[165349.20, 136897.80, 471784.10]])
output

array([[192480.59612014]])

In [65]:
#Taking the input from the user
print("Enter the ammount you will spend on:")
RDSpend = float(input("RD : "))
Administration = float(input("Admistration : "))
MarketingSpend = float(input("Marketing : "))

#predicting the profit with respect to the inputs
output = multiple_reg.predict([[RDSpend, Administration, MarketingSpend]])
print("you will get {} profit by spending {} on RD , {} on adminisration and {} on marketing.".format(output[0] if output else "not predictable", RDSpend, Administration, MarketingSpend))

Enter the ammount you will spend on:
RD : 451285.20
Admistration : 784512.30
Marketing : 789456.30
you will get [413731.86817543] profit by spending 451285.2 on RD , 784512.3 on adminisration and 789456.3 on marketing.
