In [1]:
#Importing the liabrary
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
#Importing the dataset
df = pd.read_csv("/content/Social_Network_Ads.csv")
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [33]:
#Initialising the variable
X = df.drop(['Purchased'], axis =1)
Y = df['Purchased'].values.reshape(-1,1)

In [34]:
#Splitting the dataset into training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [35]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train) 
X_test = sc_X.transform(X_test)

In [36]:
#Training the model using KNN algorithm
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [37]:
#Testing our model
Y_pred = classifier.predict(X_test)
Y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [38]:
#Making confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[48  4]
 [ 3 25]]


0.9125

In [42]:
output = classifier.predict(sc_X.transform([[35, 20000]]))
output

array([0])

In [44]:
#Predict the new result
#Taking the input from the user
print("Users input for Logistic Regression")
Age = float(input("Age : "))
EstimatedSalary = float(input("Estimatedsalary : "))


#predicting the result using input 
output = classifier.predict(sc_X.transform([[Age, EstimatedSalary]]))
print("you will Purchased {} at the age of {} having Rs{} as Estimatedsalalry." .format(output[0] if output else "not predictable",Age, EstimatedSalary))

Users input for Logistic Regression
Age : 20
Estimatedsalary : 30000
you will Purchased not predictable at the age of 20.0 having Rs30000.0 as Estimatedsalalry.
