In [ ]:
#importing the liabrary
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [ ]:
#Importing the dataset
df = pd.read_csv("/content/Social_Network_Ads.csv")
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
#Initialising the variable
X = df.drop(['Purchased'], axis =1)
Y = df['Purchased'].values.reshape(-1,1)

In [ ]:
#Splitting the dataset into training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train) 
X_test = sc_X.transform(X_test)


In [ ]:
#Training the model using logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#Testing our model
Y_pred = classifier.predict(X_test)
Y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [22]:
#Making confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[50  2]
 [ 9 19]]


0.8625

In [ ]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(Y_test, Y_pred))

Accuracy :  0.8625


In [ ]:
output = classifier.predict([[30, 70000]])
output

array([1])

In [19]:
#Predict the new result
#Taking the input from the user
print("Users input for Logistic Regression")
Age = float(input("Age : "))85
EstimatedSalary = float(input("Estimatedsalary : "))


#predicting the result using input 
output = classifier.predict([[Age, EstimatedSalary]])
print("you will Purchased {} at the age of {} having Rs{} as Estimatedsalalry." .format(output[0] if output else "not predictable",Age, EstimatedSalary)) 



Users input for Logistic Regression
Age : 19
Estimatedsalary : 85000
you will Purchased 1 at the age of 19.0 having Rs85000.0 as Estimatedsalalry.
